#+title: Todo

* admin
** voyage aida
** 11h traiteur Thalassa
** Chercher cannelets Montparnasse
** Chercher champagne / vin
** DONE bar bulle à bulle
** pot
*** DONE Réserver tables
*** TODO Réserver flutes

* commentaires
** Aida
*** Choix de paramètres pourraient être mieux justifiés
- coefficients de normalisation
- année 2007 pour calcul des coefs
par simplicité, maintenant que les outils et la méthode sont en place on peut le faire sur 2000-2020. Les coefficients ne sont pas beaucoup modifiés.
- seuil de 75% pour la fin du bloom
c'est très juste, on pourrait essayer différents seuils et regarder si ça change le résultat

*** utilisation d'histogrammes
"intéressant de regarder les données non-agrégées"
je comprends pas bien. Il ne devrait pas y avoir de différence entre les deux approches

*** test sensibilité 1km vs 4km
elle aurait aimé voir les résultats que l'on mentionne à ce sujet
Pas dispo. On avait fait des tests sur 2007, il y a longtemps (début 2021), qui montraient peu de différences dans les valeurs de chl front/background entre 1 et 4km.
Mais la méthode était pas finalisée à cette époque, donc c'est difficile de juste ressortir un résultat comme ça.
Ça montre également la difficulté de travailler avec des données L2, en regardant mes logs avec le recul, je peux voir différents problèmes (notamment techniques) qui apparaissent (et que je serais plus à même de résoudre aujourd'hui).

*** efficacité de la méthode
Il est vrai qu'on ne montre que très peu d'exemples de fronts.
Ça a pourtant été fait, j'ai regardé des centaines d'images de SST, HI et Chl pour trouver des exemples de fronts.
Globalement il me parait que les fronts de SST sont trouvés. La réponse de la Chl est rarement visible à l'oeil nu de manière très nette. C'est aussi pour ça qu'on ne montre que peu d'exemples.

On pourrait approfondir la différence entre plusieurs méthodes de détection des fronts. Certaines sont triviales à implementer (je pense à BOA).
Ça reste quand même un travail important.

Jusqu'à quelle échelle on a coincidence spatiale entre Chl et SST ?
Je dirais que pour répondre à cette question on pourrait avoir une approche plus statistique comme celle de Keerthi, mais je m'y connais pas assez pour savoir comment gérer l'aspect de coincidence entre SST et Chl.
En partant de mon travail, je pense que l'on doit regarder l'épaisseur de la  zone frontale (comme discuté en section III 3.2). Mais ça nécessite de paramétriser cette épaisseur (voir sa direction par rapport au centre du front), et donc sans doute partir d'une méthode comme celle de Cayula-Cornillon par ex. pour obtenir position et angle.
C'est très intéressant mais ça sort du cadre de ce qu'on fait je pense.

*** Timing du bloom
Évolution du timing pendant 20 ans ?
D'une part le timing absolu est très variable. Il faut vraiment se concentrer sur l'écart entre front et background.
Tout ce qui touche à l'évolution décennale va se heurter à de potentiels biais sur les capteurs satellites. Il n'y (a priori) pas de continuité parfaite dans les données et j'approcherai ça avec grande précaution.
C'est pour ça que ce n'est pas un aspect que l'on a présenté, même si ça présente très peu de travail de tracer l'évolution décennale.

*** Perspectives
Application globale n'est pas nécessairement traitement global.
C'est très très juste, et je remercie de le souligner.
En réalité ce travail a déjà commencé par l'application à des régions spécifiques (CCE, bientôt en méditerranée dans le cadre du projet 4DMED).
Ça souligne peut être le besoin de travailler sur un produit qui puisse être adapté aux différentes régions ?

*** Capteurs hyper-spectraux ?
** Hubert
*** Pourquoi la région du GS en particulier ?
Une des raisons qui nous a poussé vers cette région -et que je me rends compte que je n'ai pas discuté dans le manuscrit- c'est que l'on (notre équipe) connait bien cette zone grâce à beaucoup d'études par modèles numériques.
Lévy et al. 2001 (JMR), Lévy et al. 2012 (GRL), Lévy et al. 2012 (Ocean Modelling), Lévy et al. 2015 (JRSI), et plus récemment Mangolte et al. 2022 (JPR).
*** affectent backscatter p6
Je vois l'erreur, c'est parce que j'ai plus l'habitude de la terminologie des images de synthèse où l'on ne considère que la surface et pas le volume (et où backscatter correspont au rayonnement diffus renvoyé par la surface), d'où ma confusion.
Merci pour cette correction.
*** lien vers nasa oceancolour broken
*** inversion des produits SST et Chl
je suis clairement pas expert sur ces sujets. C'est une faiblesse notamment pour ce qui est de l'utilisation des produits L2 MODIS, où il faut être un peu plus familier avec les traitements.
Je me suis intéressé surtout à la chl, et même là je n'ai pas tellement mis le doigt dans l'engrenage de la validation des données satellites. Je sais que la répartitions des mesures in-situ est importante dans l'estimation des incertitudes. L'algorithme utilisé également.
Néanmoins, nos résultats portent surtout sur les structures spatiales observées, dont on peut espèrer sont bien représentées par le produit de chl (même si la valeur absolue pourrait être éloignée de la réalité).
*** sélection du jeux de données
On ne s'est pas limité à une seule image. J'ai travaillé et exploré chacun des produits pendant un certain temps, en regardant les images sur plusieurs années. Nous étions encore dans une phase exploratoire de la méthodologie et donc n'avons pas vraiment de comparaison directe avec les résultats présentés.
*** Effet de la SST
il faut un plot de l'effet local des fronts sur la SST, par bande de lat.
*** Effet local important quand même pour le reste de la chaine trophique
C'est vrai qu'on s'est concentré sur l'effet actif des fronts, et pas l'effet réactif des prédateurs.
D'une part le constat reste le même je pense, si l'impact sur tout le biome est de quelques %, il sera aussi de quelques % pour les prédateurs.
Relire le papier d'Inès.
D'autre part (et surtout dans la zone subtropicale en fait), on parle de fronts de submésoéchelle qui sont éphémères, avec une durée de vie de quelques jours.
L'effet d'un front sur les prédateurs est donc d'autant plus décorrélé (temporellement et spatialement) du front lui même.
*** Durée plus longue du bloom
il y a un papier la dessus, l'avoir en tête
