#+title: Todo

* admin
** voyage aida
** bar
réservation pour ~25?
** pot
*** TODO Réserver tables
*** TODO Réserver flutes
*** TODO Demander parent apporter
- Vin de bordeaux
- Cannelets
*** TODO Trouver traiteur
- grotte de chypre ?
- le truc des tartes ?
- le thai / viet ?

* mail annonce
Bonjour à toutes et tous,

/English below/

Je suis heureux de vous convier à ma soutenance de thèse qui aura lieu le mardi 4 juillet à 14h, dans l'amphi Astier (bâtiment Esclangon) et en visioconférence, dont le lien sera communiqué ultérierement.
La soutenance sera suivie d'un pot, a priori sur l'esplanade du côté de la tour 55.

Ma thèse porte sur les impacts des fronts de sub-mésoéchelle sur la croissance, la phénologie, et la biodiversité du phytoplancton, quantifiés par imagerie satellitaire autour du Gulf Stream.
Le jury sera composé de:
Pascale Bouruet-Aubertot (SU, LOCEAN), présidente du jury
Aida Alvera-Azcàrate (Université de Liège, AGO, GHER), rapportrice
Hubert Loisel (Université du Littoral Côte d'Opale, LOG), rapporteur
Élodie Martinez (IRD, LOPS), examinatrice
Daniele Iudicone (Stazione Zoologica Anton Dohrn, Naples), examinateur
Marina Lévy (CNRS, LOCEAN), directrice de thèse
Laurent Bopp (CNRS, LMD), co-directeur de thèse

Bien cordialement,

Clément Haëck

/English/
I am happy to invite you to my PhD defense, which will take place on the 4th July at 2pm, in  the auditorium Astier (building Esclangon), as well as on video conference (the link will be shared beforehand). Please note that it will be conducted in french.
You are also welcome to join the ensuing customary drinks, probably at the ground floor somewhere the tower 55.

My PhD focuses on impacts of sub-mesoscale fronts on the growth, phenology, and biodiversity of phytoplankton, quantified by satellite imagery around the Gulf Stream.
The jury will comprise:
Pascale Bouruet-Aubertot (SU, LOCEAN), president of jury
Aida Alvera-Azcàrate (Université de Liège, AGO, GHER), reviewer
Hubert Loisel (Université du Littoral Côte d'Opale, LOG), reviewer
Élodie Martinez (IRD, LOPS), examiner
Daniele Iudicone (Stazione Zoologica Anton Dohrn, Naples), examiner
Marina Lévy (CNRS, LOCEAN), director
Laurent Bopp (CNRS, LMD), co-director

Best regards,

Clément Haëck

* Animations (vidéos)
** bloom propagating north
with histogram of lon-avg on the side ?
** region separation
with lingering trace of sep threshold ?

